# SPDX-License-Identifier: Apache-2.0
[package]
name = "canokey-protocol"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
canokey-tlv = { path = "../tlv" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
