// SPDX-License-Identifier: Apache-2.0
//! Generate the C projection by compiling the actual safe Rust contracts.
#![allow(dead_code)]
extern crate std;
use std::{string::String, vec::Vec};
#[cfg(not(test))]
#[path = "../src/contracts/device.rs"]
mod device;
#[cfg(not(test))]
#[path = "../src/contracts/storage.rs"]
mod storage;
#[cfg(test)]
use super::{device, storage};

fn header() -> String {
    let mut text = String::from(
        "/* SPDX-License-Identifier: Apache-2.0 */\n\
        /* Generated by crates/ports/codegen/abi.rs; do not edit. */\n\
        #ifndef CANOKEY_PORT_ABI_H\n#define CANOKEY_PORT_ABI_H\n",
    );
    for (name, value) in [
        ("CK_RECORD_COUNT", storage::Record::COUNT),
        (
            "CK_RECORD_NDEF_CAPABILITY",
            storage::Record::NdefCapability.id() as usize,
        ),
        (
            "CK_RECORD_NDEF_MESSAGE",
            storage::Record::NdefMessage.id() as usize,
        ),
        ("CK_CHIP_ID_BYTES", device::CHIP_ID_BYTES),
        (
            "CK_BOARD_INFO_FIRMWARE",
            device::board_info_kind::FIRMWARE as usize,
        ),
        (
            "CK_BOARD_INFO_PRODUCT",
            device::board_info_kind::PRODUCT as usize,
        ),
        ("CK_BOARD_INFO_CORE", device::board_info_kind::CORE as usize),
        (
            "CK_BOARD_INFO_CHIP_ID",
            device::board_info_kind::CHIP_ID as usize,
        ),
    ] {
        text.push_str(&std::format!("#define {name} 0x{value:02X}u\n"));
    }
    text.push_str("#endif\n");
    text
}

fn main() {
    let text = header();
    let args: Vec<String> = std::env::args().collect();
    assert_eq!(
        args.len(),
        3,
        "usage: abi-generator --output|--check <header>"
    );
    match args[1].as_str() {
        "--output" => std::fs::write(&args[2], text).expect("write C ABI header"),
        "--check" => assert_eq!(
            std::fs::read_to_string(&args[2]).expect("read C ABI header"),
            text,
            "C ABI header differs from Rust contracts; regenerate it"
        ),
        _ => panic!("expected --output or --check"),
    }
}

#[test]
fn committed_c_header_matches_contracts() {
    assert_eq!(header(), include_str!("../include/port_abi.h"));
}
