#ifndef CANOKEY_CORE_OPENPGP_OPENPGP_H
#define CANOKEY_CORE_OPENPGP_OPENPGP_H

#include <apdu.h>
#include <pin.h>

#define OPENPGP_INS_SELECT 0xA4
#define OPENPGP_INS_GET_DATA 0xCA
#define OPENPGP_INS_VERIFY 0x20
#define OPENPGP_INS_CHANGE_REFERENCE_DATA 0x24
#define OPENPGP_INS_RESET_RETRY_COUNTER 0x2C

#define TAG_AID 0x4F
#define TAG_LOGIN 0x5E
#define TAG_URL 0x5F50u
#define TAG_HISTORICAL_BYTES 0x5F52u
#define TAG_CARDHOLDER_RELATED_DATA 0x65
#define TAG_NAME 0x5B
#define TAG_LANG 0x5F2Du
#define TAG_SEX 0x5F35u
#define TAG_APPLICATION_RELATED_DATA 0x6E
#define TAG_DISCRETIONARY_DATA_OBJECTS 0x73
#define TAG_EXTENDED_CAPABILITIES 0xC0
#define TAG_ALGORITHM_ATTRIBUTES_SIG 0xC1
#define TAG_ALGORITHM_ATTRIBUTES_DEC 0xC2
#define TAG_ALGORITHM_ATTRIBUTES_AUT 0xC3
#define TAG_PW_STATUS 0xC4
#define TAG_KEY_FINGERPRINTS 0xC5
#define TAG_CA_FINGERPRINTS 0xC6
#define TAG_KEY_GENERATION_DATES 0xCD
#define TAG_SECURITY_SUPPORT_TEMPLATE 0x7A
#define TAG_DIGITAL_SIG_COUNTER 0x93
#define TAG_CARDHOLDER_CERTIFICATE 0x7F21u

extern pin_t pw1, pw3, rc;

int openpgp_initialize(void);
int openpgp_process_apdu(const CAPDU *capdu, RAPDU *rapdu);

#endif // CANOKEY_CORE_OPENPGP_OPENPGP_H
