// SPDX-License-Identifier: Apache-2.0
//! ML-DSA responses splice generated bytes and a certificate into small framing
//! bytes. All three views alias the sole session workspace; nothing is cached in FS.
use super::Status;
use crate::{
    ports::{
        CryptoScratch, DigestOperation as Hash, HashState, Platform, Record, StreamOperation as Op,
        alg,
    },
    runtime::workspace::SessionWorkspace,
};
use canokey_protocol::{cbor::Encoder, der::der_signature, response::StatusWord as Sw};
pub(super) const PUBLIC_BYTES: usize = 1952;
pub(super) const SIGNATURE_BYTES: usize = 3309;
const FRAMING_BYTES: usize = 768;
#[derive(Clone, Copy)]
pub enum Mode {
    Make,
    Assert,
    Public,
}
#[derive(Clone, Copy)]
pub struct Pending {
    pub mode: Mode,
    pub prefix: usize,
    pub auth: usize,
    pub public_at: usize,
    pub signature_at: usize,
    pub certificate: Option<(usize, usize)>,
    pub output: usize,
    pub hash_prefix: (usize, usize),
    pub hash_suffix: (usize, usize),
}
// Framing survives primitive initialization, but never aliases its opaque state.
struct Framing {
    bytes: [u8; FRAMING_BYTES],
    length: usize,
    seed: [u8; 32],
    client_hash: [u8; 32],
}
pub struct Stream {
    crypto: CryptoScratch,
    framing: Framing,
    generated_at: usize,
    generated_length: usize,
    certificate_at: usize,
    certificate_length: usize,
    emitted: usize,
}
enum PartSource {
    Framing(usize),
    Generated,
    Certificate,
}
struct Part {
    source: PartSource,
    length: usize,
}
impl Stream {
    pub(crate) fn clear(&mut self, memory: &crate::ports::MemoryPort<'_>) {
        memory.wipe(&mut self.crypto.bytes);
        memory.wipe(&mut self.framing.bytes);
        memory.wipe(&mut self.framing.seed);
        memory.wipe(&mut self.framing.client_hash);
        self.framing.length = 0;
        self.generated_at = 0;
        self.generated_length = 0;
        self.certificate_at = 0;
        self.certificate_length = 0;
        self.emitted = 0;
    }
    // Transfer has its own frame, which is gone before invoking expensive crypto.
    #[inline(never)]
    fn empty() -> Self {
        Self {
            crypto: CryptoScratch::new(),
            framing: Framing {
                bytes: [0; FRAMING_BYTES],
                length: 0,
                seed: [0; 32],
                client_hash: [0; 32],
            },
            generated_at: 0,
            generated_length: 0,
            certificate_at: 0,
            certificate_length: 0,
            emitted: 0,
        }
    }

    fn fill(stream: &mut Self, plan: Pending, old: &crate::runtime::workspace::Workspace) {
        if matches!(plan.mode, Mode::Make | Mode::Public) {
            stream.framing.bytes[..plan.output].copy_from_slice(&old.output[..plan.output]);
            stream.framing.client_hash.copy_from_slice(&old.input[..32]);
            stream.framing.seed.copy_from_slice(&old.input[32..64]);
        } else {
            stream.framing.bytes[..plan.prefix].copy_from_slice(&old.output[..plan.prefix]);
            stream.framing.bytes[plan.prefix..plan.prefix + plan.auth]
                .copy_from_slice(&old.input[..plan.auth]);
            stream.framing.bytes[plan.prefix + plan.auth..plan.output + plan.auth]
                .copy_from_slice(&old.output[plan.prefix..plan.output]);
            stream
                .framing
                .seed
                .copy_from_slice(&old.input[plan.auth + 32..plan.auth + 64]);
            stream
                .framing
                .client_hash
                .copy_from_slice(&old.input[plan.auth..plan.auth + 32]);
        }
        stream.generated_at = match plan.mode {
            Mode::Make | Mode::Public => plan.public_at,
            Mode::Assert => plan.signature_at + plan.auth,
        };
        stream.generated_length = if matches!(plan.mode, Mode::Assert) {
            SIGNATURE_BYTES
        } else {
            PUBLIC_BYTES
        };
        stream.certificate_at = plan
            .certificate
            .map_or(plan.output + plan.auth, |(at, _)| at);
        stream.certificate_length = plan.certificate.map_or(0, |(_, n)| n);
    }

    #[inline(never)]
    fn transfer(
        plan: Pending,
        w: &mut SessionWorkspace,
        p: &mut Platform<'_>,
    ) -> Result<(), Status> {
        if plan.output + plan.auth > FRAMING_BYTES {
            return Err(Status::Other);
        }
        let old_workspace = core::mem::replace(w, SessionWorkspace::CtapStream(Self::empty()));
        let SessionWorkspace::Classic(mut old) = old_workspace else {
            unreachable!()
        };
        let SessionWorkspace::CtapStream(stream) = w else {
            unreachable!()
        };
        stream.framing.length = plan.output + plan.auth;
        Self::fill(stream, plan, &old);
        old.clear(p.memory);
        let SessionWorkspace::CtapStream(_) = w else {
            unreachable!()
        };
        Ok(())
    }
    pub fn prepare(
        plan: Pending,
        w: &mut SessionWorkspace,
        p: &mut Platform<'_>,
    ) -> Result<usize, Status> {
        Self::transfer(plan, w, p)?;
        let SessionWorkspace::CtapStream(stream) = w else {
            unreachable!()
        };
        let result = stream.initialize(plan, p);
        p.memory.wipe(&mut stream.framing.seed);
        p.memory.wipe(&mut stream.framing.client_hash);
        if result.is_err() {
            stream.close(p);
        }
        result.map(|()| stream.len())
    }
    fn init(&mut self, op: Op, p: &mut Platform<'_>) -> Result<usize, Status> {
        p.device.keepalive(false);
        p.crypto
            .stream(
                op,
                alg::MLDSA65,
                &mut self.crypto,
                &self.framing.seed,
                &mut [],
            )
            .map_err(|_| Status::Other)
    }
    fn initialize(&mut self, plan: Pending, p: &mut Platform<'_>) -> Result<(), Status> {
        match plan.mode {
            Mode::Make => {
                if self.init(Op::PublicInit, p)? != PUBLIC_BYTES {
                    return Err(Status::Other);
                }
                // The stream API exposes public bytes only while the primitive
                // is open. Close it after hashing the first public view, then
                // reopen it to emit the response; retaining a second 1952-byte
                // copy would exceed the shared workspace budget.
                let mut hash = HashState {
                    bytes: [0; crate::ports::HASH_STATE_BYTES],
                };
                let digest_result = self.attestation_digest(plan, &mut hash, p);
                let _ = p.crypto.digest(Hash::Abort, &mut hash, &[], &mut []);
                let _ = p
                    .crypto
                    .stream(Op::Abort, alg::MLDSA65, &mut self.crypto, &[], &mut []);
                let digest = digest_result?;
                self.attest(plan.signature_at + plan.auth, &digest, p)?;
                // PublicInit is intentionally repeated: the primitive exposes
                // the public key only through its live stream and retaining a
                // second 1952-byte copy would exceed the shared workspace.
                if self.init(Op::PublicInit, p)? != PUBLIC_BYTES {
                    return Err(Status::Other);
                }
            }
            Mode::Assert => {
                self.init(Op::SignInit, p)?;
                p.crypto
                    .stream(
                        Op::SignUpdate,
                        alg::MLDSA65,
                        &mut self.crypto,
                        &self.framing.bytes[plan.prefix..plan.prefix + plan.auth],
                        &mut [],
                    )
                    .map_err(|_| Status::Other)?;
                p.crypto
                    .stream(
                        Op::SignUpdate,
                        alg::MLDSA65,
                        &mut self.crypto,
                        &self.framing.client_hash,
                        &mut [],
                    )
                    .map_err(|_| Status::Other)?;
                if p.crypto
                    .stream(Op::SignFinal, alg::MLDSA65, &mut self.crypto, &[], &mut [])
                    .map_err(|_| Status::Other)?
                    != SIGNATURE_BYTES
                {
                    return Err(Status::Other);
                }
            }
            Mode::Public => {
                if self.init(Op::PublicInit, p)? != PUBLIC_BYTES {
                    return Err(Status::Other);
                }
            }
        }
        Ok(())
    }
    fn attestation_digest(
        &mut self,
        plan: Pending,
        hash: &mut HashState,
        p: &mut Platform<'_>,
    ) -> Result<[u8; 32], Status> {
        p.crypto
            .digest(Hash::Init, hash, &[], &mut [])
            .map_err(|_| Status::Other)?;
        p.crypto
            .digest(
                Hash::Update,
                hash,
                &self.framing.bytes[plan.hash_prefix.0..plan.hash_prefix.0 + plan.hash_prefix.1],
                &mut [],
            )
            .map_err(|_| Status::Other)?;
        let mut window = [0; 128];
        for offset in (0..PUBLIC_BYTES).step_by(window.len()) {
            if !p.device.progress() {
                return Err(Status::Cancelled);
            }
            let n = window.len().min(PUBLIC_BYTES - offset);
            if p.crypto
                .stream(
                    Op::Read,
                    alg::MLDSA65,
                    &mut self.crypto,
                    &[],
                    &mut window[..n],
                )
                .map_err(|_| Status::Other)?
                != n
            {
                return Err(Status::Other);
            }
            p.crypto
                .digest(Hash::Update, hash, &window[..n], &mut [])
                .map_err(|_| Status::Other)?;
        }
        p.crypto
            .digest(
                Hash::Update,
                hash,
                &self.framing.bytes[plan.hash_suffix.0..plan.hash_suffix.0 + plan.hash_suffix.1],
                &mut [],
            )
            .map_err(|_| Status::Other)?;
        p.crypto
            .digest(Hash::Update, hash, &self.framing.client_hash, &mut [])
            .map_err(|_| Status::Other)?;
        let mut digest = [0; 32];
        p.crypto
            .digest(Hash::Final, hash, &[], &mut digest)
            .map_err(|_| Status::Other)?;
        Ok(digest)
    }
    // PKE public generation is closed before the P-256 primitive runs.
    fn attest(&mut self, at: usize, digest: &[u8; 32], p: &mut Platform<'_>) -> Result<(), Status> {
        let mut key = [0; 32];
        let mut signature = [0; 73];
        let result = (|| {
            if !matches!(p.storage.load(Record::CtapAttestationKey, &mut key), Ok(32)) {
                return Err(Status::Other);
            }
            p.crypto
                .p256_sign(&key, digest, (&mut signature[..64]).try_into().unwrap())
                .map_err(|_| Status::Other)?;
            let n = der_signature(&mut signature, 64).map_err(|_| Status::Other)?;
            let mut encoded = [0; 74];
            let mut encoder = Encoder::new(&mut encoded[..]);
            encoder
                .bytes(&signature[..n])
                .finish()
                .map_err(|_| Status::Other)?;
            let count = 74 - encoder.writer().len();
            let end = self.framing.length;
            if end + count > FRAMING_BYTES {
                return Err(Status::Other);
            }
            self.framing.bytes.copy_within(at..end, at + count);
            self.framing.bytes[at..at + count].copy_from_slice(&encoded[..count]);
            self.framing.length += count;
            self.certificate_at += count;
            Ok(())
        })();
        p.memory.wipe(&mut key);
        result
    }
    pub fn len(&self) -> usize {
        self.framing.length + self.generated_length + self.certificate_length
    }
    pub fn read(&mut self, offset: usize, out: &mut [u8], p: &mut Platform<'_>) -> Result<(), Sw> {
        if offset != self.emitted || offset.checked_add(out.len()).is_none_or(|n| n > self.len()) {
            return Err(Sw::WRONG_LENGTH);
        }
        let parts = [
            Part {
                source: PartSource::Framing(0),
                length: self.generated_at,
            },
            Part {
                source: PartSource::Generated,
                length: self.generated_length,
            },
            Part {
                source: PartSource::Framing(self.generated_at),
                length: self.certificate_at - self.generated_at,
            },
            Part {
                source: PartSource::Certificate,
                length: self.certificate_length,
            },
            Part {
                source: PartSource::Framing(self.certificate_at),
                length: self.framing.length - self.certificate_at,
            },
        ];
        let count = out.len();
        let mut window = canokey_protocol::response::ReadWindow::new(offset, out);
        for part in parts {
            let (at, dest) = window.take(part.length);
            let n = dest.len();
            if dest.is_empty() {
                continue;
            }
            match part.source {
                PartSource::Generated => {
                    if p.crypto
                        .stream(Op::Read, alg::MLDSA65, &mut self.crypto, &[], dest)
                        .map_err(|_| Sw::UNABLE_TO_PROCESS)?
                        != n
                    {
                        return Err(Sw::UNABLE_TO_PROCESS);
                    }
                }
                PartSource::Certificate => p
                    .storage
                    .read_at(Record::CtapCertificate, at as u32, dest)
                    .map_err(|_| Sw::UNABLE_TO_PROCESS)?,
                PartSource::Framing(start) => {
                    dest.copy_from_slice(&self.framing.bytes[start + at..start + at + n])
                }
            }
        }
        self.emitted += count;
        Ok(())
    }
    pub fn close(&mut self, p: &mut Platform<'_>) {
        let _ = p
            .crypto
            .stream(Op::Abort, alg::MLDSA65, &mut self.crypto, &[], &mut []);
        p.memory.wipe(&mut self.crypto.bytes);
        p.memory.wipe(&mut self.framing.bytes);
        p.memory.wipe(&mut self.framing.seed);
        p.memory.wipe(&mut self.framing.client_hash);
    }
}
