// SPDX-License-Identifier: Apache-2.0
//! ML-DSA responses splice generated bytes and a certificate into small framing
//! bytes. All three views alias the sole session workspace; nothing is cached in FS.
use super::Status;
use crate::{
    ports::{
        CryptoScratch, DigestOperation as Hash, HashState, Platform, Record, StreamOperation as Op,
        alg,
    },
    runtime::workspace::{Primitive, SessionWorkspace},
};
use canokey_protocol::{cbor::Encoder, der::der_signature, response::StatusWord as Sw};
pub(super) const PUBLIC_BYTES: usize = 1952;
pub(super) const SIGNATURE_BYTES: usize = 3309;
const FRAMING_BYTES: usize = 768;
#[derive(Clone, Copy)]
pub enum Mode {
    Make,
    Assert,
    Public,
}
#[derive(Clone, Copy)]
pub struct Pending {
    pub mode: Mode,
    pub prefix: usize,
    pub auth: usize,
    pub public_at: usize,
    pub signature_at: usize,
    pub certificate: Option<(usize, usize)>,
    pub output: usize,
    pub hash_prefix: (usize, usize),
    pub hash_suffix: (usize, usize),
}
// Framing survives primitive initialization, but never aliases its opaque state.
#[repr(C)]
pub(crate) struct Framing {
    length: usize,
    generated_at: usize,
    generated_length: usize,
    certificate_at: usize,
    certificate_length: usize,
    emitted: usize,
    // clientDataHash followed by the ML-DSA seed, matching classic input.
    material: [u8; 64],
    pub(crate) bytes: [u8; FRAMING_BYTES],
}
impl Framing {
    pub(crate) const fn new() -> Self {
        Self {
            bytes: [0; FRAMING_BYTES],
            length: 0,
            material: [0; 64],
            generated_at: 0,
            generated_length: 0,
            certificate_at: 0,
            certificate_length: 0,
            emitted: 0,
        }
    }
    #[inline(never)]
    pub(crate) fn clear(&mut self, memory: &crate::ports::MemoryPort<'_>) {
        memory.wipe(&mut self.bytes);
        memory.wipe(&mut self.material);
        self.length = 0;
        self.generated_at = 0;
        self.generated_length = 0;
        self.certificate_at = 0;
        self.certificate_length = 0;
        self.emitted = 0;
    }
}
pub struct Stream<'a> {
    pub(crate) crypto: &'a mut CryptoScratch,
    pub(crate) framing: &'a mut Framing,
}
enum PartSource {
    Framing(usize),
    Generated,
    Certificate,
}
struct Part {
    source: PartSource,
    length: usize,
}
impl Stream<'_> {
    #[inline(never)]
    fn transfer(
        plan: Pending,
        w: &mut SessionWorkspace,
        p: &mut Platform<'_>,
    ) -> Result<(), Status> {
        if plan.output + plan.auth > FRAMING_BYTES {
            return Err(Status::Other);
        }
        let SessionWorkspace::Working(w) = w else {
            unreachable!()
        };
        let Primitive::Classic(old) = &mut w.primitive else {
            unreachable!()
        };
        let framing = &mut w.framing;
        // The output is already in its final backing. Only assertion authData
        // must be inserted between the encoded prefix and suffix.
        framing
            .bytes
            .copy_within(plan.prefix..plan.output, plan.prefix + plan.auth);
        framing.bytes[plan.prefix..plan.prefix + plan.auth]
            .copy_from_slice(&old.input[..plan.auth]);
        framing
            .material
            .copy_from_slice(&old.input[plan.auth..plan.auth + 64]);
        framing.length = plan.output + plan.auth;
        p.memory.wipe(&mut framing.bytes[framing.length..]);
        old.clear(p.memory);
        w.primitive = Primitive::Ctap(CryptoScratch::new());
        framing.generated_at = match plan.mode {
            Mode::Make | Mode::Public => plan.public_at,
            Mode::Assert => plan.signature_at + plan.auth,
        };
        framing.generated_length = if matches!(plan.mode, Mode::Assert) {
            SIGNATURE_BYTES
        } else {
            PUBLIC_BYTES
        };
        framing.certificate_at = plan.certificate.map_or(framing.length, |(at, _)| at);
        framing.certificate_length = plan.certificate.map_or(0, |(_, n)| n);
        framing.emitted = 0;
        Ok(())
    }
    pub fn prepare(
        plan: Pending,
        w: &mut SessionWorkspace,
        p: &mut Platform<'_>,
    ) -> Result<usize, Status> {
        Self::transfer(plan, w, p)?;
        let mut stream = w.ctap_stream().unwrap();
        let result = stream.initialize(plan, p);
        p.memory.wipe(&mut stream.framing.material);
        if result.is_err() {
            stream.close(p);
        }
        result.map(|()| stream.len())
    }
    fn init(&mut self, op: Op, p: &mut Platform<'_>) -> Result<usize, Status> {
        p.device.keepalive(false);
        p.crypto
            .stream(
                op,
                alg::MLDSA65,
                self.crypto,
                &self.framing.material[32..],
                &mut [],
            )
            .map_err(|_| Status::Other)
    }
    fn initialize(&mut self, plan: Pending, p: &mut Platform<'_>) -> Result<(), Status> {
        match plan.mode {
            Mode::Make => self.initialize_make(plan, p)?,
            Mode::Assert => {
                self.init(Op::SignInit, p)?;
                p.crypto
                    .stream(
                        Op::SignUpdate,
                        alg::MLDSA65,
                        self.crypto,
                        &self.framing.bytes[plan.prefix..plan.prefix + plan.auth],
                        &mut [],
                    )
                    .map_err(|_| Status::Other)?;
                p.crypto
                    .stream(
                        Op::SignUpdate,
                        alg::MLDSA65,
                        self.crypto,
                        &self.framing.material[..32],
                        &mut [],
                    )
                    .map_err(|_| Status::Other)?;
                if p.crypto
                    .stream(Op::SignFinal, alg::MLDSA65, self.crypto, &[], &mut [])
                    .map_err(|_| Status::Other)?
                    != SIGNATURE_BYTES
                {
                    return Err(Status::Other);
                }
            }
            Mode::Public => {
                if self.init(Op::PublicInit, p)? != PUBLIC_BYTES {
                    return Err(Status::Other);
                }
            }
        }
        Ok(())
    }
    // Registration-only hash/signature temporaries must not remain live on
    // the ML-DSA assertion signing path.
    #[inline(never)]
    fn initialize_make(&mut self, plan: Pending, p: &mut Platform<'_>) -> Result<(), Status> {
        if self.init(Op::PublicInit, p)? != PUBLIC_BYTES {
            return Err(Status::Other);
        }
        // The stream API exposes public bytes only while the primitive
        // is open. Close it after hashing the first public view, then
        // reopen it to emit the response; retaining a second 1952-byte
        // copy would exceed the shared workspace budget.
        let mut hash = HashState {
            bytes: [0; crate::ports::HASH_STATE_BYTES],
        };
        let digest_result = self.attestation_digest(plan, &mut hash, p);
        let _ = p.crypto.digest(Hash::Abort, &mut hash, &[], &mut []);
        let _ = p
            .crypto
            .stream(Op::Abort, alg::MLDSA65, self.crypto, &[], &mut []);
        let digest = digest_result?;
        self.attest(plan.signature_at + plan.auth, &digest, p)?;
        // PublicInit is intentionally repeated: the primitive exposes
        // the public key only through its live stream and retaining a
        // second 1952-byte copy would exceed the shared workspace.
        if self.init(Op::PublicInit, p)? != PUBLIC_BYTES {
            return Err(Status::Other);
        }
        Ok(())
    }
    fn attestation_digest(
        &mut self,
        plan: Pending,
        hash: &mut HashState,
        p: &mut Platform<'_>,
    ) -> Result<[u8; 32], Status> {
        p.crypto
            .digest(Hash::Init, hash, &[], &mut [])
            .map_err(|_| Status::Other)?;
        p.crypto
            .digest(
                Hash::Update,
                hash,
                &self.framing.bytes[plan.hash_prefix.0..plan.hash_prefix.0 + plan.hash_prefix.1],
                &mut [],
            )
            .map_err(|_| Status::Other)?;
        let mut window = [0; 128];
        for offset in (0..PUBLIC_BYTES).step_by(window.len()) {
            if !p.device.progress() {
                return Err(Status::Cancelled);
            }
            let n = window.len().min(PUBLIC_BYTES - offset);
            if p.crypto
                .stream(Op::Read, alg::MLDSA65, self.crypto, &[], &mut window[..n])
                .map_err(|_| Status::Other)?
                != n
            {
                return Err(Status::Other);
            }
            p.crypto
                .digest(Hash::Update, hash, &window[..n], &mut [])
                .map_err(|_| Status::Other)?;
        }
        p.crypto
            .digest(
                Hash::Update,
                hash,
                &self.framing.bytes[plan.hash_suffix.0..plan.hash_suffix.0 + plan.hash_suffix.1],
                &mut [],
            )
            .map_err(|_| Status::Other)?;
        p.crypto
            .digest(Hash::Update, hash, &self.framing.material[..32], &mut [])
            .map_err(|_| Status::Other)?;
        let mut digest = [0; 32];
        p.crypto
            .digest(Hash::Final, hash, &[], &mut digest)
            .map_err(|_| Status::Other)?;
        Ok(digest)
    }
    // PKE public generation is closed before the P-256 primitive runs.
    fn attest(&mut self, at: usize, digest: &[u8; 32], p: &mut Platform<'_>) -> Result<(), Status> {
        let mut key = [0; 32];
        let mut signature = [0; 73];
        let result = (|| {
            super::attestation::key(&mut key, p).map_err(|_| Status::Other)?;
            p.crypto
                .p256_sign(&key, digest, (&mut signature[..64]).try_into().unwrap())
                .map_err(|_| Status::Other)?;
            let n = der_signature(&mut signature, 64).map_err(|_| Status::Other)?;
            // A P-256 DER signature is at most 72 bytes, so its CBOR
            // byte-string header occupies one or two bytes.
            let count = n + if n < 24 { 1 } else { 2 };
            let end = self.framing.length;
            if end + count > FRAMING_BYTES {
                return Err(Status::Other);
            }
            self.framing.bytes.copy_within(at..end, at + count);
            Encoder::new(&mut self.framing.bytes[at..at + count])
                .bytes(&signature[..n])
                .finish()
                .map_err(|_| Status::Other)?;
            self.framing.length += count;
            self.framing.certificate_at += count;
            Ok(())
        })();
        p.memory.wipe(&mut key);
        result
    }
    pub fn len(&self) -> usize {
        self.framing.length + self.framing.generated_length + self.framing.certificate_length
    }
    pub fn read(&mut self, offset: usize, out: &mut [u8], p: &mut Platform<'_>) -> Result<(), Sw> {
        if offset != self.framing.emitted
            || offset.checked_add(out.len()).is_none_or(|n| n > self.len())
        {
            return Err(Sw::WRONG_LENGTH);
        }
        let parts = [
            Part {
                source: PartSource::Framing(0),
                length: self.framing.generated_at,
            },
            Part {
                source: PartSource::Generated,
                length: self.framing.generated_length,
            },
            Part {
                source: PartSource::Framing(self.framing.generated_at),
                length: self.framing.certificate_at - self.framing.generated_at,
            },
            Part {
                source: PartSource::Certificate,
                length: self.framing.certificate_length,
            },
            Part {
                source: PartSource::Framing(self.framing.certificate_at),
                length: self.framing.length - self.framing.certificate_at,
            },
        ];
        let count = out.len();
        let mut window = canokey_protocol::response::ReadWindow::new(offset, out);
        for part in parts {
            let (at, dest) = window.take(part.length);
            let n = dest.len();
            if dest.is_empty() {
                continue;
            }
            match part.source {
                PartSource::Generated => {
                    if p.crypto
                        .stream(Op::Read, alg::MLDSA65, self.crypto, &[], dest)
                        .map_err(|_| Sw::UNABLE_TO_PROCESS)?
                        != n
                    {
                        return Err(Sw::UNABLE_TO_PROCESS);
                    }
                }
                PartSource::Certificate => p
                    .storage
                    .read_at(Record::CtapCertificate, at as u32, dest)
                    .map_err(|_| Sw::UNABLE_TO_PROCESS)?,
                PartSource::Framing(start) => {
                    dest.copy_from_slice(&self.framing.bytes[start + at..start + at + n])
                }
            }
        }
        self.framing.emitted += count;
        Ok(())
    }
    pub fn close(&mut self, p: &mut Platform<'_>) {
        let _ = p
            .crypto
            .stream(Op::Abort, alg::MLDSA65, self.crypto, &[], &mut []);
        p.memory.wipe(&mut self.crypto.bytes);
        self.framing.clear(p.memory);
    }
}

#[cfg(test)]
mod tests;
