FROM ubuntu:24.04

ARG UBUNTU_MIRROR
RUN if [ -n "${UBUNTU_MIRROR}" ]; then \
        if [ -s /etc/apt/sources.list ]; then \
            sed -i.bak "s|http://archive.ubuntu.com/ubuntu|${UBUNTU_MIRROR}|g" /etc/apt/sources.list; \
        elif [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then \
            sed -i.bak "s|http://archive.ubuntu.com/ubuntu|${UBUNTU_MIRROR}|g" /etc/apt/sources.list.d/ubuntu.sources; \
        fi; \
    fi

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends \
    git gcc g++ cmake pkg-config psmisc procps make \
    pcscd pcsc-tools \
    libhidapi-dev libssl-dev libpcsclite-dev libudev-dev libusb-1.0-0-dev \
    libcmocka-dev libcbor-dev zlib1g-dev \
    patch swig \
    python3-dev python3-pip python3-setuptools python3-wheel python3-jsonschema python3-jinja2 python3-venv \
  && rm -rf /var/lib/apt/lists/*

COPY test-via-pcsc /root/test-via-pcsc

RUN cd /root && ./test-via-pcsc/build_fido_tests.sh && ./test-via-pcsc/install_fido_tests.sh

WORKDIR /root
USER root
