// SPDX-License-Identifier: Apache-2.0
// Fixed GetInfo schema tokens. Values controlled by card state stay in info.rs.
use minicbor::{Encoder, encode::Error};
use std::{convert::Infallible, fmt::Write};
type E = Encoder<Vec<u8>>;
type R = Result<(), Error<Infallible>>;
fn fragment(out: &mut String, name: &str, encode: impl FnOnce(&mut E) -> R) {
    let mut e = E::new(Vec::new());
    encode(&mut e).unwrap();
    writeln!(out, "const {name}: &[u8] = &{:?};", e.writer()).unwrap();
}
pub fn generate_info() {
    let mut out = String::from("// Generated by codegen/ctap.rs; do not edit.\n");
    fragment(&mut out, "HEADER", |e| {
        e.map(22)?.u8(1)?;
        Ok(())
    });
    fragment(&mut out, "U2F", |e| {
        e.str("U2F_V2")?;
        Ok(())
    });
    fragment(&mut out, "VERSIONS_EXTENSIONS", |e| {
        e.str("FIDO_2_0")?
            .str("FIDO_2_1")?
            .str("FIDO_2_3")?
            .u8(2)?
            .array(7)?
            .str("credBlob")?
            .str("credProtect")?
            .str("minPinLength")?
            .str("largeBlobKey")?
            .str("hmac-secret")?
            .str("hmac-secret-mc")?
            .str("thirdPartyPayment")?
            .u8(3)?;
        Ok(())
    });
    fragment(&mut out, "OPTIONS", |e| {
        e.u8(4)?
            .map(10)?
            .str("rk")?
            .bool(true)?
            .str("up")?
            .bool(true)?
            .str("alwaysUv")?;
        Ok(())
    });
    fragment(&mut out, "CLIENT_PIN", |e| {
        e.str("credMgmt")?
            .bool(true)?
            .str("authnrCfg")?
            .bool(true)?
            .str("clientPin")?;
        Ok(())
    });
    fragment(&mut out, "OPTIONS_END", |e| {
        e.str("largeBlobs")?
            .bool(true)?
            .str("pinUvAuthToken")?
            .bool(true)?
            .str("setMinPINLength")?
            .bool(true)?
            .str("makeCredUvNotRqd")?
            .bool(true)?
            .u8(5)?;
        Ok(())
    });
    fragment(&mut out, "PIN_PROTOCOLS", |e| {
        e.u8(6)?.array(2)?.u8(1)?.u8(2)?.u8(7)?;
        Ok(())
    });
    fragment(&mut out, "ALGORITHMS", |e| {
        e.u8(9)?.array(1)?.str("usb")?.u8(10)?.array(4)?;
        for algorithm in [-7, -8] {
            e.map(2)?
                .str("alg")?
                .i32(algorithm)?
                .str("type")?
                .str("public-key")?;
        }
        e.map(2)?.str("alg")?;
        Ok(())
    });
    fragment(&mut out, "ALGORITHMS_END", |e| {
        e.str("type")?
            .str("public-key")?
            .map(2)?
            .str("alg")?
            .i8(-49)?
            .str("type")?
            .str("public-key")?
            .u8(11)?;
        Ok(())
    });
    fragment(&mut out, "LIMITS", |e| {
        e.u8(14)?.u8(0)?.u8(15)?.u8(32)?.u8(16)?.u8(4)?.u8(20)?;
        Ok(())
    });
    fragment(&mut out, "RESET", |e| {
        e.u8(22)?.array(1)?.str("packed")?.u8(24)?;
        Ok(())
    });
    fragment(&mut out, "END", |e| {
        e.u8(26)?
            .array(2)?
            .str("nfc")?
            .str("usb")?
            .u8(29)?
            .u8(63)?
            .u8(31)?
            .array(3)?
            .u8(2)?
            .u8(3)?
            .u8(4)?;
        Ok(())
    });
    let path = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    std::fs::write(path.join("ctap_info.rs"), out).unwrap();
}

pub fn generate_response() {
    let mut out = String::from("// Generated by codegen/ctap.rs; do not edit.\n");
    // Keep invariant response fields out of the device's encoding call graph.
    fragment(&mut out, "MAKE_HEADER", |e| {
        e.map(3)?.u8(1)?.str("packed")?.u8(2)?;
        Ok(())
    });
    fragment(&mut out, "SELF_ATTESTATION", |e| {
        e.map(2)?.str("alg")?;
        Ok(())
    });
    fragment(&mut out, "ATTESTATION", |e| {
        e.map(3)?.str("alg")?.i8(-7)?.str("sig")?;
        Ok(())
    });
    fragment(&mut out, "CERTIFICATE", |e| {
        e.str("x5c")?.array(1)?;
        Ok(())
    });
    fragment(&mut out, "DESCRIPTOR", |e| {
        e.map(2)?.str("id")?;
        Ok(())
    });
    fragment(&mut out, "PUBLIC_KEY_TYPE", |e| {
        e.str("type")?.str("public-key")?;
        Ok(())
    });
    for (name, value) in [
        ("USER_ID", "id"),
        ("USER_NAME", "name"),
        ("USER_DISPLAY", "displayName"),
    ] {
        fragment(&mut out, name, |e| {
            e.str(value)?;
            Ok(())
        });
    }
    for (name, kind, algorithm) in [("COSE_ED25519", 1, -8), ("COSE_MLDSA65", 7, -49)] {
        fragment(&mut out, name, |e| {
            e.map(4)?
                .u8(1)?
                .u8(kind)?
                .u8(3)?
                .i8(algorithm)?
                .i8(-1)?
                .u8(6)?
                .i8(-2)?;
            Ok(())
        });
    }
    fragment(&mut out, "COSE_EC2", |e| {
        e.map(5)?.u8(1)?.u8(2)?.u8(3)?;
        Ok(())
    });
    fragment(&mut out, "KEY_AGREEMENT", |e| {
        e.map(1)?
            .u8(1)?
            .map(5)?
            .u8(1)?
            .u8(2)?
            .u8(3)?
            .i8(-25)?
            .i8(-1)?
            .u8(1)?
            .i8(-2)?;
        Ok(())
    });
    let path = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    std::fs::write(
        path.join("ctap_response.rs"),
        out.replace("const ", "pub(super) const "),
    )
    .unwrap();
}
