# SPDX-License-Identifier: Apache-2.0
[package]
name = "canokey-test-card"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false
[[bin]]
name = "apdu-replay"
path = "src/bin/replay.rs"
required-features = ["replay"]
[[bin]]
name = "apdu-fuzzer"
path = "src/bin/fuzz.rs"
required-features = ["fuzz"]
[[bin]]
name = "core-behavior"
path = "src/bin/behavior.rs"
required-features = ["behavior"]
[dependencies]
canokey-rust-core = { path = "../../crates/core" }
canokey-protocol = { path = "../../crates/protocol" }
canokey-ports = { path = "../../crates/ports", default-features = false, features = ["native-crypto"] }
libc = { version = "=0.2.189", optional = true }
libfuzzer-sys = { version = "=0.4.13", optional = true }
[features]
default = []
behavior = []
replay = ["dep:libc"]
fuzz = ["dep:libfuzzer-sys", "dep:libc"]
admin = ["canokey-rust-core/admin"]
pass = ["canokey-rust-core/pass"]
oath = ["canokey-rust-core/oath"]
openpgp = ["canokey-rust-core/openpgp"]
piv = ["canokey-rust-core/piv"]
ctap = ["canokey-rust-core/ctap"]
ndef = ["canokey-rust-core/ndef"]
ctap-restrict-algorithms = ["ctap", "canokey-rust-core/ctap-restrict-algorithms"]
[lints]
workspace = true
