# SPDX-License-Identifier: Apache-2.0
[package]
name = "canokey-rust-core"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false
build = "build.rs"
[dependencies]
canokey-protocol = { path = "../protocol" }
[build-dependencies]
cfg_aliases = "0.2.1"
minicbor = { version = "=2.3.0", path = "../../minicbor/minicbor", features = ["std"] }
[features]
admin = []
ctap = []
openpgp = []
piv = []

default = []
pass = []
oath = []

[dev-dependencies]
sha2 = "0.10.9"

[lints]
workspace = true
