# SPDX-License-Identifier: Apache-2.0
[package]
name = "canokey-rust-core"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
canokey-protocol = { path = "../protocol" }
canokey-pass = { path = "../pass", default-features = false, optional = true }

[features]
default = []
pass = ["dep:canokey-pass"]
c-interface = []
host-runtime = []

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
