# SPDX-License-Identifier: Apache-2.0
[package]
name = "canokey-rust-core"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false
[dependencies]
canokey-protocol = { path = "../protocol" }
[features]
admin = []
openpgp = []
piv = []

default = []
pass = []
oath = []

[dev-dependencies]
sha2 = "0.10.9"
