# SPDX-License-Identifier: Apache-2.0
set(CANOKEY_PROFILE "full" CACHE STRING "Host composition: full, none, admin-pass, oath, openpgp, piv, ctap, custom")
set_property(CACHE CANOKEY_PROFILE PROPERTY STRINGS full none admin-pass oath openpgp piv ctap custom)
set(profile_full ADMIN PASS OATH OPENPGP PIV CTAP NDEF)
set(profile_none "")
set(profile_admin-pass ADMIN PASS)
set(profile_oath ADMIN PASS OATH)
set(profile_openpgp ADMIN PASS OATH OPENPGP)
set(profile_piv PIV)
set(profile_ctap ADMIN CTAP)
if(NOT CANOKEY_PROFILE MATCHES "^(full|none|admin-pass|oath|openpgp|piv|ctap|custom)$")
  message(FATAL_ERROR "Unknown CANOKEY_PROFILE: ${CANOKEY_PROFILE}")
endif()
foreach(applet ADMIN PASS OATH OPENPGP PIV CTAP NDEF)
  option(CANOKEY_APPLET_${applet} "Enable ${applet} in the custom host profile" OFF)
  if(NOT CANOKEY_PROFILE STREQUAL "custom")
    set(CANOKEY_APPLET_${applet} OFF)
    if(applet IN_LIST profile_${CANOKEY_PROFILE})
      set(CANOKEY_APPLET_${applet} ON)
    endif()
  endif()
endforeach()
set(FEATURES host-runtime,static-backend)
foreach(applet ADMIN PASS OATH OPENPGP PIV CTAP NDEF)
  if(CANOKEY_APPLET_${applet})
    string(TOLOWER "${applet}" feature)
    string(APPEND FEATURES ",${feature}")
  endif()
endforeach()
if(CTAP_RESTRICT_ALGORITHMS)
  if(NOT CANOKEY_APPLET_CTAP)
    message(FATAL_ERROR "Algorithm restriction requires CTAP in the selected profile")
  endif()
  string(APPEND FEATURES ,ctap-restrict-algorithms)
endif()
set(full_host OFF)
if(CANOKEY_PROFILE STREQUAL "full")
  set(full_host ON)
endif()
option(CANOKEY_VIRTUAL_CARD "Build the complete Rust virtual card" ${full_host})
option(CANOKEY_APDU_REPLAY "Build the correctness APDU replay tool" OFF)
# Retained command-line spelling; there is only one build entrypoint.
if(ENABLE_APDU_REPLAY)
  set(CANOKEY_APDU_REPLAY ON)
endif()
if(CANOKEY_VIRTUAL_CARD OR CANOKEY_APDU_REPLAY OR CANOKEY_FUZZING)
  foreach(applet ADMIN PASS OATH OPENPGP PIV CTAP NDEF)
    if(NOT CANOKEY_APPLET_${applet})
      message(FATAL_ERROR "Host tools require the full applet set: missing ${applet}")
    endif()
  endforeach()
endif()
