# SPDX-License-Identifier: Apache-2.0
# Platforms supply an absolute configuration path; core never reads parent paths.
if(DEFINED CANOKEY_VERSIONS_FILE)
    include("${CANOKEY_VERSIONS_FILE}")
elseif(CANOKEY_RELEASE)
    message(FATAL_ERROR "Release builds require CANOKEY_VERSIONS_FILE")
else()
    message(STATUS "No release version configuration: using development-only zero versions")
    set(CANOKEY_FIDO_FIRMWARE_VERSION 0)
    set(CANOKEY_CTAPHID_DEVICE_VERSION "0.0.0")
    set(CANOKEY_USB_BCD_DEVICE 0x0000)
    set(CANOKEY_PIV_VERSION "0.0.0")
    set(CANOKEY_OATH_VERSION "0.0.0")
endif()

set(version_header "/* Generated release fields. Protocol versions belong in implementation code. */\n#pragma once\n")
foreach(field CTAPHID_DEVICE PIV OATH)
    if(NOT CANOKEY_${field}_VERSION MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$")
        message(FATAL_ERROR "CANOKEY_${field}_VERSION must contain three decimal bytes")
    endif()
    set(parts "${CMAKE_MATCH_1};${CMAKE_MATCH_2};${CMAKE_MATCH_3}")
    set(index 0)
    foreach(part IN LISTS parts)
        if(part GREATER 255 OR part MATCHES "^0[0-9]+")
            message(FATAL_ERROR "CANOKEY_${field}_VERSION components must be 0..255 without leading zeros")
        endif()
        string(APPEND version_header "#define CANOKEY_${field}_VERSION_${index} ${part}\n")
        math(EXPR index "${index}+1")
    endforeach()
endforeach()
if(NOT CANOKEY_FIDO_FIRMWARE_VERSION MATCHES "^(0|[1-9][0-9]*)$" OR
   CANOKEY_FIDO_FIRMWARE_VERSION GREATER 4294967295)
    message(FATAL_ERROR "CANOKEY_FIDO_FIRMWARE_VERSION must be a uint32 decimal integer")
endif()
if(NOT CANOKEY_USB_BCD_DEVICE MATCHES "^0x[0-9][0-9][0-9][0-9]$")
    message(FATAL_ERROR "CANOKEY_USB_BCD_DEVICE must contain exactly four BCD digits")
endif()
string(APPEND version_header "#define FIRMWARE_VERSION ${CANOKEY_FIDO_FIRMWARE_VERSION}\n#define CANOKEY_USB_BCD_DEVICE ${CANOKEY_USB_BCD_DEVICE}\n")
set(CANOKEY_RELEASE_VERSION_HEADER "${CMAKE_CURRENT_BINARY_DIR}/firmware-version.h")
if(EXISTS "${CANOKEY_RELEASE_VERSION_HEADER}")
    file(READ "${CANOKEY_RELEASE_VERSION_HEADER}" existing_header)
endif()
if(NOT existing_header STREQUAL version_header)
    file(WRITE "${CANOKEY_RELEASE_VERSION_HEADER}" "${version_header}")
endif()
