/* SPDX-License-Identifier: Apache-2.0 */
/* Generated by crates/ports/codegen/abi.rs; do not edit. */
#ifndef CANOKEY_PORT_ABI_H
#define CANOKEY_PORT_ABI_H
#define CK_RECORD_COUNT 0xBAu
#define CK_RECORD_NDEF_CAPABILITY 0xB8u
#define CK_RECORD_NDEF_MESSAGE 0xB9u
#define CK_CHIP_ID_BYTES 0x0Du
#define CK_BOARD_INFO_FIRMWARE 0x00u
#define CK_BOARD_INFO_PRODUCT 0x01u
#define CK_BOARD_INFO_CORE 0x02u
#define CK_BOARD_INFO_CHIP_ID 0x03u
#endif
